assets_root: assets


data_ingestion:
  root_dir: assets/data_ingestion
  source_URL: https://www.kaggle.com/datasets/vasudevmaduri/fedexdata
  local_data_file: assets/data_ingestion/fedexdata.zip
  unzip_dir: assets/data_ingestion

data_validation:
  root_dir: assets/data_validation
  unzip_data_dir: assets/data_ingestion/fedex.csv
  STATUS_FILE: assets/data_validation/status.txt

data_transformation:
  root_dir: assets/data_transformation
  data_path: assets/data_ingestion/fedex.csv

